version: '3'
services:
    backend:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - xero-api

    xero-api:
        image: jaypeng2015/show-me-the-money
        ports:
            - "3000:3000"
