version: "3.8" # Or any version compatible with your Docker setup

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: "0.0.0.0"
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    command: ["npm", "run", "start"]
